### ISSUE TITLE
Slant Rounds: sure about dividing degree angle by 100?

### ISSUE THREAD

**Issue by mekkablue** [alexeiva/alexei-glyphs-scripts#3]
Or did you mean something like this:

First at the top, add:

```python
from math import radians
```

Then in `process()`, replace the myX/Y assignments with this:

```python
	myY =  radians(thisMasterAngle)
	myX = -radians(thisMasterAngle)
```

And this change to the shear matrix:

```python
	thisLayer.applyTransform([1, myX/2, myY, 1, 0, 0])
```

Or what exactly is Jacques’ method, spelled out in words?

**Comment by alexeiva** [comment]
Thank you for the suggestion. /100 was simply my closest guess. Radians is exactly what I was looking for, as it produces a mathematically natural result, and is identical to the slant in Glyphs.

```
Given Italic angle is 10:
old transform: applyTransform([1, -0.100000, 0.200000, 1, 0, 0])
new transform: applyTransform([1, -0.087266, 0.174533, 1, 0, 0]) radians(thisMasterAngle)
```
> Or what exactly is Jacques’ method, spelled out in words?

Jacques @fonthausen mentioned a skew with *0.5 compensation. 
`vSkew = 0.5 * i | hSkew = i `, where `i = Italic Angle`
<img width="484" alt="screen shot 2018-02-26 at 2 56 04 pm" src="https://user-images.githubusercontent.com/16634089/36666779-18e72166-1b05-11e8-845a-e49714316c6d.png">

I tried an alternative method, it produces similar results:
`vSkew = i | hSkew = i + 2`
<img width="488" alt="screen shot 2018-02-26 at 2 56 07 pm" src="https://user-images.githubusercontent.com/16634089/36666791-223989ac-1b05-11e8-9806-9aa2bb7c465c.png">
